### PR TITLE
Do not fatal error when the host does not match the portal

### LINKED ISSUE #724: FatalError when no host is matched
e.g. trying to run sulu-standard on `127.0.0.1` instead of `sulu.lo` gives:

````
FatalErrorException: Error: Call to a member function getWebspace() on null in /home/daniel/www/sulu-cmf/sulu/src/Sulu/Bundle/WebsiteBundle/EventListener/SetThemeEventListener.php line 36
````

### PR DESCRIPTION
**Pull request by dantleech**
- Do not try and set the theme on non-existant portal

Fixes #724 

__Tasks:__

- [x] test coverage
- [ ] gather feedback for my changes

__Informations:__

| Q             | A
| ------------- | ---
| Tests pass?   | yes
| Fixed tickets | 
| BC Breaks     | [description]
| Doc           | [url to commit|none]

### CODE REVIEW

File: src/Sulu/Component/Webspace/Analyzer/WebsiteRequestAnalyzer.php [hunk 1]
```diff
@@ -128,45 +128,47 @@ public function analyze(Request $request)
...
+            $request->setRequestFormat($format);
+        }
+
+        // get the resource locator prefix and set it
+        $this->setCurrentResourceLocatorPrefix(
+            substr(
+                $portalInformation->getUrl(),
+                strlen($request->getHost())
+            )
+        );
```
Comment (dantleech) [inline src/Sulu/Component/Webspace/Analyzer/WebsiteRequestAnalyzer.php]: Removed all the `else` statements from this method
