### PR TITLE
Fixed redirect with port

### LINKED ISSUE #716: Homepage redirect moves the :port to the end of the URL. Breaks.
If you are running

````
http://localhost:8001
````

You will be redirected to:

````
http://localhost/en:8001
````

### PR DESCRIPTION
**Pull request by dantleech**
Fix redirect when there is a `:port` in the URL.

Fixes #716

### CODE REVIEW

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php [hunk 1]
```diff
@@ -64,4 +62,38 @@ public function redirectAction(Request $request)
...
+    /**
+     * Resolve the redirect URL, appending any additional path data
+     *
+     * @param string $url Original webspace URI
+     * @param string $redirectUrl  Redirect webspace URI
+     * @param string $requestUri The actual incoming request URI
+     *
+     * @return string URL to redirect to
+     */
+    protected function resolveRedirectUrl($portalUrl, $redirectUrl, $requestUri)
```
Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: Should probably be private as this is basically evil and should be somewhere else.

Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: maybe we should delete the redirectWebspaceAction and move resolveRedirectUrl into our ContentRouteProvider.php and call then the normal redirectAction at https://github.com/sulu-cmf/sulu/blob/b40ddca685e0e53a5d95b00f6dcf1826c41c8ac7/src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php#73#L73

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php [hunk 2]
```diff
@@ -64,4 +62,38 @@ public function redirectAction(Request $request)
...
+            sprintf('{%s(:.*?)?/(.*)}', $portalUrl),
+            sprintf('%s/\2', $redirectUrl),
+            $requestUri
+        );
+
+        if ($port) {
+            $url = preg_replace('{(http://)?(.*?)/(.*)$}', sprintf('\1\2%s/\3', $port), $url);
+        }
+
+        $url = rtrim($url, '/');
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: We should use pathInfo or a Symfony equivalent function to split the url in Domain/Path/Query. Because only the Path should be rtrim currently the redirects dont work when had a query string. e.g.
sulu.lo/?id=12, sulu.lo?id=12, sulu.lo/articles/?id=12, sulu.lo/articles/?id=12

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php (hunk 1 above)
Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: Sounds like it might work

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php (hunk 2 above)
Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: Will have a look today

**Comment by dantleech** [comment]
@alexander-schranz updated to use the php `parse_url` function, it now supports query and fragments.

Not sure how to refactor it upstream though.. I can't see a good way to do it without refactoring. Maybe @danrot can advise.

If not I suggest we merge this as-is.

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php [hunk 3]
```diff
@@ -64,4 +61,64 @@ public function redirectAction(Request $request)
...
+
+        if (isset($requestInfo['port'])) {
+            $url .= ':' . $requestInfo['port'];
+        }
+
+        if (isset($redirectInfo['path'])) {
+            $url .= $redirectInfo['path'];
+        }
+
+        if (isset($requestInfo['path'])) {
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: why requestInfo path added to $url?

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php [hunk 4]
```diff
@@ -64,4 +61,64 @@ public function redirectAction(Request $request)
...
+        $requestInfo = $this->parseUrl($requestUri);
+
+        $url = sprintf('%s://%s', $requestInfo['scheme'], $redirectInfo['host']);
+
+        if (isset($requestInfo['port'])) {
+            $url .= ':' . $requestInfo['port'];
+        }
+
+        if (isset($redirectInfo['path'])) {
+            $url .= $redirectInfo['path'];
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: shouldnt this be rtrim(.., '/')

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php (hunk 3 above)
Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: given `/sulu.lo/foobar` with a portal `sulu.io/en` then the request info path is `/foobar` and should be added to `/en`

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php (hunk 4 above)
Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: We remove the trailing slash at the end of this function.

Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: you need to add the rtrim to the path not at the end of the function e.g.
http://www.sulu.io/en/test/?trimblocker=1 -> http://www.sulu.io/en/test?trimblocker=1
http://www.sulu.io/en/test/#trimblocker -> http://www.sulu.io/en/test#trimblocker

Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: ack. will add a test

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php (hunk 3 above)
Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: can it be that the '/foobar' is '/en/foobar' and we get problems then adding the '/en' which will result in '/en/en/foobar' or is this not possible?

Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: I did have a test for this, but if we had `/en/foobar` there wouldn't be any redirect right?

Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: `/en/foobar/` needed to be redirect to `/en/foobar` but i'm not sure if this goes over the redirectWebspaceAction

Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: @dantleech Have you checked this issue?

File: src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php [hunk 5]
```diff
@@ -27,30 +27,48 @@ protected function setUp()
...
 
-    public function testRedirectActionWithTrailingSlash()
+    public function provideRedirectAction()
     {
-        $request = $this->getRequestMock('sulu-redirect.lo/', 'sulu-redirect.lo', 'sulu.lo');
+        return array(
+            array('http://sulu.lo/articles?foo=bar', 'sulu.lo', 'sulu.lo/en', 'http://sulu.lo/en/articles?foo=bar'),
+            array('http://sulu.lo/articles?foo=bar&bar=boo', 'sulu.lo', 'sulu.lo/en', 'http://sulu.lo/en/articles?foo=bar&bar=boo'),
+            array('sulu.lo:8001/', 'sulu.lo', 'sulu.lo/en', 'http://sulu.lo:8001/en'),
+            array('sulu.lo:8001/#foobar', 'sulu.lo', 'sulu.lo/en', 'http://sulu.lo:8001/en/#foobar'),
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php]: I guess that's what @alexander-schranz meant, the result here should be `http://sulu.lo:8001/en/#foobar`

Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php]: right should be `http://sulu.lo:8001/en#foobar`

Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php]: @chirimoya what do you think about that?

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php (hunk 3 above)
Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: I guess if the locale is in the domain we might get this

Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: But then the redirect should not be triggered by the RouteProvider.

Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: Confirmed. `sulu.lo/articles` redirects fine to `en.sulu.lo/articles`

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php [hunk 6]
```diff
@@ -64,4 +61,65 @@ public function redirectAction(Request $request)
...
+        }
+
+        if (isset($requestInfo['path'])) {
+            $url .= $requestInfo['path'];
+
+            if (substr($url, -1) == '/') {
+                $url = substr($url, 0, -1);
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: Why don't you just use `$url = rtrim($url, '/')`?

Comment (dantleech) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: use rtrim
