### PR TITLE
fixes zero byte upload

### LINKED ISSUE #753: Upload with 0 bytes file dont work

### PR DESCRIPTION
**Pull request by alexander-schranz**
__Tasks:__

- [ ] test coverage
- [ ] gather feedback for my changes
- [x] added changelog line

__Informations:__

| Q             | A
| ------------- | ---
| Tests pass?   | none
| Fixed tickets | fixes #753 
| BC Breaks     | no
| Doc           | none

### CODE REVIEW

File: src/Sulu/Bundle/MediaBundle/Media/FileValidator/DefaultFileValidator.php [hunk 1]
```diff
@@ -57,7 +57,7 @@ public function validate (UploadedFile $file, $methods = array(
             throw new InvalidFileTypeException('The file type was blocked');
         }
 
-        if (in_array(self::VALIDATOR_MAX_FILE_SIZE, $methods) && $file->getSize() <= $this->maxFileSize) {
+        if (in_array(self::VALIDATOR_MAX_FILE_SIZE, $methods) && $this->maxFileSize !== null && $file->getSize() >= $this->maxFileSize) {
             throw new MaxFileSizeExceededException('The file is to big');
```
Comment (dantleech) [inline src/Sulu/Bundle/MediaBundle/Media/FileValidator/DefaultFileValidator.php]: `sprintf(File size for "%s" is bigger than max filesize "%s"', $file->getFilename(), $this->maxFilesize)` ?

Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Media/FileValidator/DefaultFileValidator.php]: did update the error messages and make the PR  merge able. error in contact bundle i think come not from this PR?

Comment (dantleech) [inline src/Sulu/Bundle/MediaBundle/Media/FileValidator/DefaultFileValidator.php]: there was/is a failing test in ContactBundle for import, @christianbader had a look at it earlier

File: src/Sulu/Bundle/MediaBundle/Media/FileValidator/DefaultFileValidator.php [hunk 2]
```diff
@@ -46,19 +46,19 @@ public function validate (UploadedFile $file, $methods = array(
...
 
         if (in_array(self::VALIDATOR_BLOCK_FILE_TYPES, $methods) && in_array($file->getMimeType(), $this->blockedMimeTypes)) {
-            throw new InvalidFileTypeException('The file type was blocked');
+            throw new InvalidFileTypeException(sprintf('The file type "%s" was blocked', $file->getMimeType()));
         }
 
-        if (in_array(self::VALIDATOR_MAX_FILE_SIZE, $methods) && $file->getSize() <= $this->maxFileSize) {
-            throw new MaxFileSizeExceededException('The file is to big');
+        if (in_array(self::VALIDATOR_MAX_FILE_SIZE, $methods) && $this->maxFileSize !== null && $file->getSize() >= $this->maxFileSize) {
+            throw new MaxFileSizeExceededException(sprintf('File "%s" exceeds the [configured?] maximum filesize of "%s"', $file->getFilename(), $this->maxFilesize));
```
Comment (dantleech) [inline src/Sulu/Bundle/MediaBundle/Media/FileValidator/DefaultFileValidator.php]: Do we not know if it is configured?

Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Media/FileValidator/DefaultFileValidator.php]: sry need to delete the configured? :) 
When its the server limit and not an own configured limit it will be the first error (VALIDATOR_FILE_ERRORS) and will not come to this also $file->getSize then dont exists.

**Comment by dantleech** [comment]
Should there be a test here?

**Comment by alexander-schranz** [comment]
@dantleech  test added

File: src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php [hunk 3]
```diff
@@ -569,6 +569,40 @@ public function testPostWithoutDetails()
     }
 
     /**
+     * @description Test POST to create a new Media without details
```
Comment (dantleech) [inline src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php]: Hmm that not a PHPUnit annotation right?

Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php]: oh righty right

Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php]: @dantleech  I deleted @description the from functions

**Comment by alexander-schranz** [comment]
@dantleech merge conficts solved

**Comment by dantleech** [comment]
Bam.

**Comment by alexander-schranz** [comment]
@dantleech thx
@michaelzangerle zero file upload fixed!
